0xPolygon/polygon-cli

cmd/monitor/monitor.go, metrics/metrics.go
While monitoring the `zkevm` testnet, we noticed that many blocks have the same timestamp. For example, I found that 150 blocks have the same timestamp. Unfortunately, `polycli` compares blocks based on their timestamp but we don't handle the case where blocks have the same timestamp... In this case, we should compare the block numbers.
This is why the blocks are not rendered in the right order.
- [DVT-501]()
Blocks are now rendered in the correct order.
[DVT-501]: https://polygon.atlassian.net/browse/DVT-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: zkevm block order

cmd/forge/block_reader.go, cmd/forge/forge.go, cmd/forge/receipt_reader.go, rpctypes/rpctypes.go
- Adds block rewards to `forge`
- Supply a receipts file with `--receipts`
- Set the `--base-block-reward`
- Include transaction fees with `--tx-fees=true`
- Currently only supports `json`
- [DVT-380](https://polygon.atlassian.net/browse/DVT-380)
```bash
go run main.go forge --genesis genesis.json --mode json --blocks poa-core.0.to.100k.blocks --count 99999 --tx-fees=true --receipts poa-core.0.to.100k.receipts --base-block-reward 1000000000000000000
```
- Output: `1:17PM TRC blockNumber=55 blockReward=1026960700000000000`
- Verified here: https://blockscout.com/poa/core/block/55/transactions
[DVT-380]: https://polygon.atlassian.net/browse/DVT-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DVT-380] Add block rewards

cmd/abi/abi.go, cmd/parseethwallet/parseethwallet.go, cmd/root.go
Adding a simple command that can take a basic key file that's generated from Geth and convert it into an easier to work with hex formatted private key. In a pinch, we needed to extract the private key from a file that uses the [Web3 Secret Storage Definition](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition). 
This is a quick example:
=> Extract keys from go-ethereum formatted file

.github/workflows/release.yml
Minor CI change to avoid moving up to 1.20 until we upgrade our dependencies properly.
=> ci: specifying 1.19 since some deps cant handle 1.20 yet

go.mod, go.sum
Use `github.com/opencontainers/runc v1.1.4`.
See https://github.com/maticnetwork/polygon-cli/security/dependabot/11
x
x
=> fix: github.com/opencontainers/runc vulnerability

metrics/metrics.go
- Moves `Block Hash` and `Author` columns further down. 
- [DVT-602](https://polygon.atlassian.net/browse/DVT-602)
[DVT-602]: https://polygon.atlassian.net/browse/DVT-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DVT-602] Re-arrange columns

cmd/loadtest/loadtest.go
The summarization didn’t include all of the transactions for some reason.
To fix this, I removed a `continue` statement when building the block data in order to keep empty receipts. This way, the number of total transactions should be equal to the `samples` number given by the user.
- [DVT-597]()
[DVT-597]: https://polygon.atlassian.net/browse/DVT-597
=> fix: summarization issue

go.mod, go.sum
Fix the `runc` vulnerability issue.
Follow-up task of a previous PR https://github.com/maticnetwork/polygon-cli/pull/50.
x
=> fix: upgrade to `github.com/opencontainers/runc` `v1.1.5`

cmd/loadtest/loadtest.go
adds dynamic rate limiting in the [AIMD fashion](https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/d071f3da1e8e5b646e220525783eb2ba_MIT6_033S18lec11.pdf). more specifically, we periodically query the rpc tx_pool status to gauge whether we should increase or back off our loadtest request rate. 
https://polygon.atlassian.net/browse/DVT-604
**successfully builds and running against dev geth locally via following cmd:**
`polycli loadtest --verbosity 700 --chain-id 1337 --concurrency 1 --requests 2000 --adaptive-rate-limit=true --steady-state-tx-pool-size 100 --adaptive-rate-limit-start 5 --adaptive-rate-limit-increment 10 --adaptive-cycle-duration-seconds 20 --mode t http://127.0.0.1:8545
**log sample results:**
> 1:54PM DBG Starting main loadtest loop …
=> [DVT-604] add adaptive rate limiting feature

README.md, cmd/monitor/monitor.go, metrics/metrics.go
- Fixes batch flag
- Improves logging
- Reduces lag when navigating through the block list
- Sparklines now follow the active window in realtime
- One caveat is that this implementation doesn't have the "lookback" feature.
- I think this command needs a refactor. I tried some refactoring, but I got a little overwhelmed. Maybe breaking the refactoring into another ticket would be good.
- [DVT-638](https://polygon.atlassian.net/browse/DVT-638)
```
go run main.go monitor https://polygon-rpc.com -v 500 -l monitor.log -b 100
```
https://user-images.githubusercontent.com/18576915/230434627-2468db18-580b-4d0d-800b-a246d6c601e0.mov
[DVT-638]: https://polygon.atlassian.net/browse/DVT-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DVT-638] Fix batch flag

Makefile, cmd/loadtest/loadtest.go
The number of contract call tries was hardcoded to 30 in `polycli` (around 30 seconds). In certain scenario, we'd like to specify a longer waiting time. Instead of relying on time durations, we'll use block numbers which makes more sense in the context of blockchains.
This PR introduces two new parameters, `contract-call-nb-blocks-to-wait-for` which defines the number of blocks to wait for before giving up on a contract call (default: 30 blocks) and `contract-call-block-interval` which defines the number of blocks to wait between contract calls (default: 1 block). This PR also updates the logic of `blockUntilSuccessful` including the support of `context` to allow the function to be canceled early.
- [DVT-502](https://polygon.atlassian.net/browse/DVT-502)
```sh
$ polycli loadtest -h | grep …
```
=> feat: allow to configure the number of tries when making a contract call

Makefile, cmd/parseethwallet/parseethwallet.go, hdwallet/hdwallet.go
Adding a simple method to run the opposite direction as the current `parseethwallet` method. Given a raw hex encoded private key, we should be able to create a keystore.
Additionally as part of the PoS automation, we need a way to export the uncompressed public key, so we're adding a field `HexFullPublicKey` to the `wallet` command which would output the full key which is used by our staking scripts.
[DVT-711](https://polygon.atlassian.net/browse/DVT-711)
[DVT-711]: https://polygon.atlassian.net/browse/DVT-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding ability to create geth/bor style wallet from hex

cmd/loadtest/loadtest.go, go.mod, go.sum
Switch to a better maintained version of the `avail/substrate` fork.
- Former fork: https://github.com/prabal-banerjee/go-substrate-rpc-client
- New fork: https://github.com/availproject/go-substrate-rpc-client
Might be worth merging this PR before we solve the issues of #71 
x
=> chore: use `availproject/go-substrate-rpc-client` fork

Makefile, cmd/loadtest/loadtest.go, go.mod, go.sum
The installation of `polycli v0.1.20` fails when using `go install` (see #70).
```bash
$ go install github.com/maticnetwork/polygon-cli@v0.1.20                                                                                                                                
go: downloading github.com/maticnetwork/polygon-cli v0.1.20
go: github.com/maticnetwork/polygon-cli@v0.1.20 (in github.com/maticnetwork/polygon-cli@v0.1.20):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```
This PR also bumps the version of go to `1.19` and adds helpers to start an `avail` dev node locally and start load testing.
x
=> fix: remove replace directive in `go.mod`

p2p/database/database.go, p2p/database/datastore.go, p2p/rlpx.go
Looks like total difficulty is just the sum of difficulties from the beginning of the chain. When receiving NewBlocks (not block hashes), you get the total difficulty, but I originally omitted this to prevent a sparsely set field since when receiving block hashes there would be no way to request it. This PR adds that here to allow during analysis to quickly calculate the total difficulty by traversing up the parents. This traversal is not done at the sensor level to prevent incurring additional reads ops.
=> write total difficulty

.gitignore, cmd/root.go, cmd/rpcfuzz/rpcfuzz.go, go.mod, go.sum, rpctypes/schemas.go, rpctypes/schemas/README.org, rpctypes/schemas/openrpc.json, rpctypes/schemas/rpcschemaaccountlist.json, rpctypes/schemas/rpcschemaethblock.json, rpctypes/schemas/rpcschemaethreceipt.json, rpctypes/schemas/rpcschemaethsyncing.json, rpctypes/schemas/rpcschemaethtransaction.json, rpctypes/schemas/rpcschemafilterchanges.json, rpctypes/schemas/rpcschemasigntxresponse.json
We build and work with a wide variety of EVM implementations. We need quick ways to verify adherence to common RPC standards across clients. E.g if some clients respond with a hex string for block numbers and others respond with a number, that's going to make integration and adoption more challenging. The goal here is to be able assess EVM clients quickly and understand if they are implement in a way that conforms to a reference implementation (geth)
The approach taken here is to have a Test object that can executed in isolation. Each test should be an independent atomic unit that can executed in any order or in parallel. Since the tests themselves are objects, they are programmable. They can be sorted, fuzzed run at high speed, etc. Over time we'll add more edge cases, fuzzing …
=> ETH JSON RPC Conformance Tests

README.md
Added requirements. 
Without "make" you cannot run the next command and without `jq`and `bc` the installation will run with errors and silently fail.
```bash
:~/polygon-cli$ make install
/bin/sh: 1: jq: not found
/bin/sh: 1: bc: not found
mkdir -p ./out
go build -ldflags "-s -w -X \"github.com/maticnetwork/polygon-cli/cmd/version.Version=dev (f96f208b)\"" -o ./out/polycli main.go
go: downloading github.com/rs/zerolog v1.27.0
go: downloading github.com/spf13/viper v1.12.0
...
```
=> Added requirements

cmd/p2p/sensor/sensor.go, cmd/p2p/sensor/sensor_util.go, p2p/database/database.go, p2p/database/datastore.go, p2p/rlpx.go
- adds `--write-block-events` and `--write-tx-events` flags to toggle whether to write events to datastore
- [DVT-801](https://polygon.atlassian.net/browse/DVT-801)
```bash
go run main.go p2p sensor nodes.json --bootnodes enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303,enode://4be7248c3a12c5f95d4ef5fff37f7c44ad1072fdb59701b2e5987c5f3846ef448ce7eabc941c5575b13db0fb016552c1fa5cca0dda1a8008cf6d63874c0f3eb7@3.93.224.197:30303,enode://32dd20eaf75513cf84ffc9940972ab17a62e88ea753b0780ea5eca9f40f9254064dacb99508337043d944c2a41b561a17deaa …
```
=> [DVT-801] Add flags for each datastore entity

README.md
Only for the command `make generate` you will also need protoc installed on your system or you will get an error.
* Added protoc as requirements for `make generate`
* Added instructions to install protoc on a Linux based system. (it was only written for mac)
=> protoc requirement

cmd/rpcfuzz/argfuzz/argfuzz.go, cmd/rpcfuzz/rpcfuzz.go, cmd/rpcfuzz/testreporter/testreporter.go
Fuzzing functionality integrated into the arguments of the JSON RPC calls, by running with the `--fuzz` flag. The fuzzer's effectiveness becomes evident through multiple iterations of running fuzzed tests (default to 100 times), with the expected outcome being an error returned by the RPC.
- [DVT-812](https://polygon.atlassian.net/browse/DVT-812?atlOrigin=eyJpIjoiZmVmNDk4MTgxYmNjNGJjNWEyYWEyMDlkODZkODQzMzgiLCJwIjoiaiJ9)
Test run:
```
$ time go run main.go rpcfuzz http://localhost:8545 --fuzz --fuzzn 5
5:32PM INF Loaded private key ethAddress=0x85dA99c8a7C2C95964c8EfD687E95E632Fc533D6
5:32PM INF enabling namespaces namespaces=["eth_","web3_","net_"]
5:32PM TRC Doing test setup
5:32PM TRC current nonce value curNonce=1
5:32PM TRC fetch chainid chainId=1337
...
5:40PM INF 1/1 Test(s) Passed …
```
=> [DVT-812] Conformance Fuzzing Library

cmd/monitor/monitor.go
If you're not doing `2> out.err` when running `polycli monitor` this log message is very disruptive. Dropping the default level for now to deal with it.
=> Log Level Change

go.mod, go.sum
Bump `go-libp2p` to `v0.27.8`
Related to: https://github.com/maticnetwork/polygon-cli/security/dependabot/13
=> fix: `go-libp2p` vulnerability

cmd/loadtest/loadtest.go
Bug fix with ERC 20 minting logic
=> fix: inverted minting logic

cmd/loadtest/loadtest.go
Minor change to avoid retrying transactions when the error is related to a re-used nonce. Without this patch, certain types of errors will happen over and over again.
=> Skipping retry for nonce related errors

cmd/loadtest/app.go, cmd/loadtest/loadtest.go, cmd/loadtest/recall.go, cmd/rpcfuzz/usage.md, doc/polycli_loadtest.md, doc/polycli_rpcfuzz.md, util/util.go
Making some fixes to the behaviors of recall mode and the call only flag. There were some bugs which caused the same tx to be used over and over again.
=> Tx Recall and Call Only Test Fixes

cmd/loadtest/loadtest.go, cmd/loadtest/loadtestmode_string.go
When using `polycli loadtest --mode random`, there is an edge with `recall` mode being called as the first random mode which will cause the program to stop. I suggest to simply remove this mode from the random modes. Or we could also just prevent this mode to being called first.
Here are the complete logs.
```sh
$ go run main.go loadtest http://localhost:8545 --mode random --requests 100 --concurrency 10 --rate-limit 100 --verbosity 700      INT at 10:40:44
10:40AM DBG Starting logger in console mode
10:40AM INF Starting Load Test
10:40AM INF Connecting with RPC endpoint to initialize load test parameters
10:40AM TRC Retrieved current gas price gasprice=201441672
10:40AM TRC Retrieved current gas tip cap gastipcap=1
10:40AM TRC Current Block Number blocknumber=12
10:40AM TRC Current …
```
=> chore: remove `recall` mode from `polycli loadtest --mode random`

Makefile
Added the `CGO_ENABLED=1` env var to build static binaries for MacOS.
Fixes #117 
- [DVT-000]()
=> feat: build static binary for macOS

cmd/loadtest/loadtest.go, cmd/rpcfuzz/rpcfuzz.go, cmd/rpcfuzz/usage.md, doc/polycli_rpcfuzz.md
- Add empty `eth_estimageGas`, `eth_sendTransaction` and `eth_sendRawTransaction` calls to `rpcfuzz`.
- Add json-rpc error code constants.
- Update `rpcfuzz` usage doc.
- [DVT-859](https://polygon.atlassian.net/browse/DVT-859)
We only keep the relevant methods to make the description shorter.
| NAME                                        | METHOD                  | TEST(S) PASSED | TEST(S) RAN |
|---------------------------------------------|-------------------------|----------------|------------|
| RPCTestEthEstimateGasEmpty                   | eth_estimateGas         | 1              | 1          |
| RPCTestEthSendRawTransactionEmpty            | eth_sendRawTransaction  | 1              | 1          |
| RPCTestEthSendTransactionEmpty               | eth_sendTransaction     | 1 …
=> feat(rpcfuzz): add empty `eth_estimageGas`, `eth_sendTransaction` and `eth_sendRawTransaction` calls to `rpcfuzz`

cmd/loadtest/app.go, cmd/loadtest/loadtest.go
When sending load test on a new chain with no blocks, the software panics. This PR avoids the division by zero and also makes sure the block interval is strictly positive (to avoid another potential division by zero).
```sh
$ polycli loadtest \
--private-key 26e86e45f6fc45ec6e2ecd128cec80fa1d1505e5507dcd2ae58c3130a7a97b48 \
--verbosity 700 \
--chain-id 1337 \
--concurrency 1 \
--requests 1000 \
--rate-limit 100 \
--mode r \
--legacy \
http://127.0.0.1:8545
9:43AM DBG Starting logger in console mode
9:43AM INF Starting Load Test
9:43AM INF Connecting with RPC endpoint to initialize load test parameters
9:43AM TRC Retrieved current gas price gasprice=1000000000
9:43AM TRC Current Block Number blocknumber=0
9:43AM TRC Current account balance balance=10000000000000000000000
9:43AM TRC Hex of …
```
=> fix(loadtest): panic when loadtesting on a new chain with no blocks 

cmd/rpcfuzz/rpcfuzz.go, doc/polycli_rpcfuzz.md
Send an RPC call with an empty array using `rpcfuzz`.
This enables to implement the following test in `rcpfuzz`: `curl -X POST -H "Content-Type: application/json" --data '[]' <url>` which returns `{"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"empty batch"}}` for both `geth` (`1.13.2-stable`) and `erigon` (`2.52.0-dev-5a8e462f`).
- [DVT-979](https://polygon.atlassian.net/browse/DVT-979)
I used the following command to test: `go run main.go rpcfuzz http://localhost:8545 --namespaces raw`. It only run the raw HTTP tests, which at the moment only consists of the empty batch test.
We only keep the relevant methods to make the description shorter.
| NAME       | METHOD | TEST(S) PASSED | TEST(S) RAN |
|------------|--------|----------------|------------|
| EmptyBatch | POST   | 1 …
=> feat(rpcfuzz): enable raw HTTP tests against any JSON-RPC

cmd/p2p/sensor/sensor.go, cmd/p2p/usage.md, doc/polycli_p2p.md
- Fixes sensor discovery
- Update usage docs
- [DVT-993](https://polygon.atlassian.net/browse/DVT-993)
[DVT-993]: https://polygon.atlassian.net/browse/DVT-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DVT-993] Fix sensor discovery

.gitignore, cmd/loadtest/app.go, cmd/loadtest/loadtest.go, cmd/loadtest/output.go, doc/polycli_loadtest.md
Some loadtest improvements:
- `time-limit` reporting loadtest summary
- legacy transaction bugfix
- fix incorrect tps calculation in light summary
- bugfix with nil rate limiter
Eg Functional ERC-721 loadtest:
```
$ go run main.go loadtest --chain-id 12321 \
--legacy \
--verbosity 700 \
--iterations 1 \
--mode 7 \
--rate-limit 40 \
--concurrency 20 \
--requests 500 http://localhost:8123/
...
4:45AM DBG got final block number currentNonce=1582198 final block number=1609581
4:45AM INF * Results
4:45AM INF Samples samples=10000
4:45AM INF Start time of loadtest (first transaction sent) startTime=2023-10-20T04:33:47Z
4:45AM INF End time of loadtest (final transaction mined) endTime=2023-10-20T04:45:46Z
4:45AM INF Estimated tps tps=13.908103300385962
4:45AM INF Mean Wait meanWait between …
```
=> Feat: loadtest improvements

cmd/loadtest/app.go, cmd/loadtest/loadtest.go, cmd/loadtest/uniswapv3/pool.go, cmd/monitor/monitor.go, doc/polycli_loadtest.md, doc/polycli_loadtest_uniswapv3.md, go.mod, go.sum
The `blockUntilSuccessful` had gotten weirdly complicated (and yet still didn't work). I was planning to add logic to estimate block intervals, but then I figured it would be better just to have a simpler time based implementation and drop some of this complicated logic. If this doesn't work, then it means there is a use case where waiting for 2 minutes doesn't work which seems surprising.
=> Block Until Successful Fix

cmd/loadtest/loadtest.go, go.mod, go.sum
- Move `completeLoadTest` inside `loopFunc` to handle cancellation signals properly.
- Document `runLoadTest` function.
- [DVT-1069](https://polygon.atlassian.net/browse/DVT-1069)
[DVT-1069]: https://polygon.atlassian.net/browse/DVT-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: `polycli loadtest` does not stop immediately when one try to interrupt it with `Ctrl+C`

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile
Follow up of #145 and #149.
- **Fix release names**. Instead of having release names with long and detailed descriptions, they're going to be shortened to just the version numbers. For instance, rather than a name like "[v0.1.35: fix: polycli loadtest does not stop immediately when one tries to int…](https://github.com/maticnetwork/polygon-cli/releases/tag/v0.1.35)", it will be simplified to just `v0.1.35`. This change aims to make release names cleaner and more concise.
- Nit: rename `test.yml` workflow into `ci.yml`.
- [DVT-1032](https://polygon.atlassian.net/browse/DVT-1032)
Create a dummy tag called `test` and push it to trigger the `release` job.
[DVT-1032]: https://polygon.atlassian.net/browse/DVT-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
=> fix: release names

README.md, cmd/monitor/cmd.go, cmd/monitor/monitor.go, doc/polycli_monitor.md, go.mod, go.sum
* implement LRU cache for
* efficient memory usage
* preventing memory leaks by limiting the number of blocks in memory
* ensure application scalability by enabling polycli monitor to run indefinitely without running out of memory.
* improve performance by automatically evicting least accessed blocks, focusing resources on recent and relevant data.
added functions
- `isBlockInCache`: Determines if a given block number is already available in the LRU cache to avoid unnecessary network requests.
- `checkAndFetchMissingBlocks`: Identifies blocks not present in the cache within a specified range and fetches them from the Ethereum network to fill the cache.
removed
- remove `currIdx`, `selectedBlock`, `Max/MinBlockRetrieved` to clean up logic variables
fix after …
=> DVT-1057 replace block data structure with LRU cache to fix memory leak

cmd/monitor/monitor.go
`polycli monitor` hangs if batch requests are disabled. In order to fix this issue, we send a sample batch request to check if the RPC supports this kind of requests before fetching any blocks. If the call fails, we return a standard error.
- [DVT-1120](https://polygon.atlassian.net/browse/DVT-1120)
I didn't want to run the `zkevm` node so I wrote a very simple [proxy](https://github.com/leovct/polygon/tree/main/tools/proxy) server that can toggle batch request support on the fly using command-line flags. The proxy forwards requests to a local node running at `localhost:8545` and returns the response to the client.
```bash
$ go run main.go monitor --rpc-url http://localhost:8080
```
```bash
$ go run main.go monitor --rpc-url http://localhost:8080
Error: batch requests are not supported …
```
=> fix: `monitor` hangs if batch requests are disabled

hdwallet/hdwallet.go
The output from `polycli wallet` outputs normal hex formatted ETH addresses. This is causing validation issues in some cases:
To fix, I'm just using the go-etherum/common package to convert the bytes to an address and then using `String()` which seems to be [EIP-55](https://github.com/ethereum/ercs/blob/master/ERCS/erc-55.md) friendly.
```
polycli wallet inspect --mnemonic 'code code code code code code code code code code code quality' | jq '.Addresses[0].ETHAddress'
```
=> EIP-55 Addresses

cmd/loadtest/app.go, cmd/loadtest/loadtest.go, cmd/loadtest/loadtestmode_string.go, doc/polycli_loadtest.md
This PR introduces a new polycli loadtest mode, `--mode contract-call`, which allows the calling of any arbitrary contract method. In order to use `--mode contract-call`, the following must be passed in:
- `--contract-address`
- `--calldata`
- if the contract function is `payable`, then the `--contract-call-payable` should also be passed in and it will use the `--eth-amount` flag as the value passed in.
Essentially, invoking `cast call` or `cast send` in a loadtest.
Some follow-up tasks would be to add:
- [DVT-1072](https://polygon.atlassian.net/browse/DVT-1072)
A simple non-state changing call (i.e. no transactions created):
```
$ cast calldata "getNumber()(uint)"
0xf2c9ecd8
$ go run main.go loadtest \
--verbosity 700 \
--mode contract-call \
--contract-address $CONTRACT_ADDRESS \ …
```
=> feat: `--mode contract-call` added

cmd/monitor/monitor.go
After creating the RPC, send a dummy transaction (e.g. get the chain ID) to check if the RPC is available. If not, return the error message. Then we can check if the RPC supports batch requests.
- [DVT-1161](https://polygon.atlassian.net/browse/DVT-1161)
[DVT-1161]: https://polygon.atlassian.net/browse/DVT-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: misleading error message in `polycli monitor`

cmd/monitor/monitor.go
Since chain id might not be implemented by all chains, let's get the latest block number to check if the RPC is available.
- [DVT-1161](https://polygon.atlassian.net/browse/DVT-1161)
[DVT-1161]: https://polygon.atlassian.net/browse/DVT-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: get block number instead of chain id to check if rpc is available

cmd/loadtest/app.go, cmd/loadtest/loadtest.go, doc/polycli_loadtest.md
This PR introduces an easy way of loadtesting arbitrary contract functions with simple function names and arguments.
It introduces 2 new flags for the `--mode contract-call` option:
- `--function-signature`: The contract's function signature that will be called. The format is `<function name>(<types...>)`
- `--function-arg`: The arguments that will be passed to the function call. Args can be passed multiple times like: `--function-arg "test" --function-arg 999` or comma separated values `--function-arg "test",9`. The ordering of the arguments must match the ordering of the function parameters.
This is a sample loadtest against the ERC721 contract.
Spin up geth in dev mode:
```
$ geth --dev --dev.period 2 --http --rpc.gascap 5000000000 --miner.gaslimit 5000000000 --dev.gaslimit 5000000000 …
```
=> feat: loadtest with arbitrary contract function calls

cmd/monitor/monitor.go, cmd/monitor/ui/ui.go
some chains have limits for the max batch processing number. to solve this, concurrent fetching by batches in 50 is implemented.
=> concurrent processing of get blocks. batches by 50 default

cmd/monitor/monitor.go
- Read lock when reading from block cache.
- [DVT-1203](https://polygon.atlassian.net/browse/DVT-1203)
[DVT-1203]: https://polygon.atlassian.net/browse/DVT-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: read lock when reading from block cache

.github/workflows/build-docker.yml, .github/workflows/build-package.yml, Dockerfile, go.mod, go.sum, packaging/deb/polycli/DEBIAN/README.md, packaging/templates/package_scripts/control
CI pipeline implemented to deploy for docker and APT
test docker : https://www.notion.so/polygontechnology/docker-install-artifact-registry-029697d8dd734241bf8762093fc5f36e?pvs=4
test apt: https://github.com/maticnetwork/polygon-devnets/pull/192/files#diff-3dbac6e0aed201ffeda73ba9a32923d2900d7550deb0a1b4f1ed4277f1d75a8eR85-R97
=> DVT-1200  configure pipeline for polycli docker deployment

.github/workflows/ci.yml, contracts/foundry.toml
Use a specific `solc` version when generating files to make sure a new `solc` release doesn't break our CI job.
See https://github.com/maticnetwork/polygon-cli/pull/192#issuecomment-1912399511
We'll migrate to `solc 0.8.24` once `forge` supports it: https://github.com/foundry-rs/foundry/issues/6903
=> fix(ci): check generated files should be reliable

cmd/monitor/cmd.go, cmd/monitor/monitor.go, doc/polycli_monitor.md
log why batch call is failing so we are not lost
i made the retry + backoff a go routine… but this still prevents ctrl+c when it’s retrying :shrug:
force stop batch retry when the error is “batch limit”
=> error when batch limit error + add sub batch arg

cmd/loadtest/loadtest.go, cmd/monitor/monitor.go, cmd/monitor/ui/ui.go, util/util.go
This PR adds the ability to track queued transactions as well along with pending txs in the `monitor` command as it's helpful for load testing.
Tested it on a devnet and queued tx count shows up correctly
=> feat: track queued txs along with pending

cmd/loadtest/app.go, cmd/loadtest/loadtest.go, cmd/loadtest/output.go, cmd/loadtest/recall.go, go.mod, go.sum
This is a minor change to support light summarization even when using rpc mode or `--call-only`. Additionally, we're changing the approach for `eth_estimateGas` to avoid making unnecessary calls to get the transaction since we already have it. This also fixes the issue where the `from` field for all of the transactions was rong.
=> Adding light summary for rpc mode

cmd/loadtest/loadtest.go
`polycli loadtest --requests 500 --legacy --rpc-url http://127.0.0.1:8545 --verbosity 700 --rate-limit 3 --mode 2 --mode 7 --private-key <private_key>`
Value for mode when iterating multi node does not match the actual int values (e.g. `loadTestModeERC20 == 6`), so the if condition does not run. This applies to all modes using legacy `mode` to check the if condition.
- [DVT-1346](https://polygon.atlassian.net/browse/DVT-1346)
```
$ polycli loadtest --requests 500 --legacy --rpc-url http://127.0.0.1:8545 --verbosity 700 --rate-limit 3 --mode "2,7" --private-key 83bc81ac77f59ba37b396874207abcf5216f6143194b2793efd969edc0eec00f
10:40AM TRC Starting logger in console mode
10:40AM INF Starting Load Test
10:40AM INF Connecting with RPC endpoint to initialize load test parameters
10:40AM TRC …
```
=> fix: multimode panic fix

cmd/loadtest/loadtest.go
While starting load test for let's say ERC 721 mints, we make a `BatchMint` call while initialising. I am not sure if making this call while initialising is expected but when this is the case, we use the latest nonce from sender during the loadtest. As the first transaction hasn't gone through yet, we receive the old nonce. I think we should use `PendingNonce` to handle such cases (or any other case where there are some pending txs already present from same sender). This PR does that. I am not sure of the repercussions of this change so would like to know your thoughts. Thanks! 
1. Create an empty devnet
2. Run load test using the following command
```
~/polygon/polygon-cli │ main !1  polycli loadtest --legacy --verbosity 501 --private-key <pk> --mode 7 --rate-limit 500 --requests 1 …
```
=> fix(loadtest): use pending nonce instead of latest

cmd/p2p/sensor/sensor.go, doc/polycli_p2p_sensor.md
Update default fork-id post Cancun/Napoli HF on Polygon Mainnet.
Earlier it wasn't able to connect to good peers due to failure in p2p Handshake. Post this fix, it is able to discover and connect to good peers.
=> sensor: update default mainnet fork-id

cmd/monitor/ui/ui.go
Fix overflowing rows in blockinfo section.
- [DVT-1511](https://polygon.atlassian.net/browse/DVT-1511)
[DVT-1511]: https://polygon.atlassian.net/browse/DVT-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: draw each blockinfo section information into separate rows

cmd/loadtest/loadtest.go
This PR disables multimode support for blobs.
Blob transactions take significantly longer than other transactions to be mined. The address sending these transactions will be reserved before these transactions are mined. This means other types of modes will not be processed.
=> fix: disable multimode loadtesting for blob transactions

cmd/fund/fund.go, hdwallet/hdwallet.go
Remove `ETHCommonAddress` field from `polycli wallet`. This field represents the same value as `ETHAddress`, but has a different type - `common.Address` compared to being a `string`. It does not add new information, and the name may be a potential cause of confusion.
**Any previous code using `ETHCommonAddress` field should now use the variable `ETHAddress` instead.**
- [DVT-1524](https://polygon.atlassian.net/browse/DVT-1524)
[DVT-1524]: https://polygon.atlassian.net/browse/DVT-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove EthCommonaddress

cmd/ulxly/ulxly.go, doc/polycli_ulxly_deposit-claim.md, doc/polycli_ulxly_deposit-new.md
This PR add onto the [previous](https://github.com/maticnetwork/polygon-cli/pull/304) uLxLy deposit and claim features with new:
* `polycli ulxly deposit-new --bridge-message` bool flag to indicate the deposit is a bridgeMessage call:
```!
/**
* @notice Bridge message and send ETH value
* note User/UI must be aware of the existing/available networks when choosing the destination network
* @param destinationNetwork Network destination
* @param destinationAddress Address destination
* @param forceUpdateGlobalExitRoot Indicates if the new global exit root is updated or not
* @param metadata Message metadata
*/
function bridgeMessage(
uint32 destinationNetwork,
address destinationAddress,
bool forceUpdateGlobalExitRoot,
bytes calldata metadata
)
```
* `polycli ulxly deposit-claim …
=> feat: ulxly bridge and claim message

cmd/ulxly/ulxly.go, doc/polycli_ulxly_deposit-claim.md, doc/polycli_ulxly_deposit-new.md
Allow `--gas-limit` to be set to `0`, which is now also the default value. This will return an estimate value for the gas limit instead of relying on user's input.
=> fix: allow 0 gas limit for gas estimation

cmd/ulxly/ulxly.go
This PR fixes the logic for querying claim payloads through the bridge service api. With multiple networks, the query logic should now also include the destination network value, because different networks will all have the same deposit count indexes which start from 0.
=> fix: ulxly claim filter logic

cmd/p2p/sensor/sensor.go, doc/polycli_p2p_sensor.md
- Adds `/info` route to sensor
- [DVT-000]()
=> feat: add node info route

cmd/fund/fund.go
Rearranged the code to generate wallets before deploying the Funder contract. The contract is now funded based on the number of wallets generated. The total fund amount is calculated by multiplying the per-wallet funding amount by the number of addresses. This ensures the contract has enough Ether to fund all generated wallets.
Now we can bulk funding wallets more than 1_000 ETH
=> fix: bulk fund wallets with massive amount

cmd/monitor/monitor.go, cmd/monitor/ui/ui.go, util/util.go
- Display the number of trusted, virtual and verified batches if the rpc supports it.
- Display the gap between virtual and trusted batches.
- Display the gap between verified and trusted batches.
- Only display tx pool status if the rpc supports it.
```bash
polycli monitor --rpc-url https://rpc.cardona.zkevm-rpc.com
```
```bash
polycli monitor --rpc-url https://rpc.cardona.zkevm-rpc.com
```
```bash
polycli monitor # local geth node
```
x
x
=> feat(monitor): add zkevm batch counters

cmd/monitor/monitor.go
- Add checks to ensure the selected block has transactions before attempting to access them.
- Implement bounds checking for the selected transaction index.
- Log errors for out-of-range selections and empty transaction lists.
https://0xpolygon.slack.com/archives/C07AWFULS49/p1726607070863549?thread_ts=1726607034.825629&cid=C07AWFULS49
```bash
polycli monitor --rpc-url https://rpc.cardona.zkevm-rpc.com
```
+ tried to scroll and explore the different blocks and txs
=> fix(monitor): out of range panics

cmd/loadtest/app.go, cmd/loadtest/loadtest.go, cmd/loadtest/loadtestmode_string.go, doc/polycli_loadtest.md
Sort `polycli loadtest` modes.
Before:
```bash
-m, --mode strings                           The testing mode to use. It can be multiple like: "t,c,d,f"
t - sending transactions
d - deploy contract
c - call random contract functions
f - call specific contract function
p - call random precompiled contracts
a - call a specific precompiled contract address
s - store mode
r - random modes
2 - ERC20 transfers
7 - ERC721 mints
v3 - UniswapV3 swaps
R - total recall
rpc - call random rpc methods
cc, contract-call - call a contract method
inscription - sending inscription transactions (default [t])
```
After:
```bash
-m, --mode strings                           The testing mode to use. It can be multiple like: "c,d,f,t"
2, erc20 - Send ERC20 tokens
7, erc721 - Mint ERC721 tokens
b, blob - Send blob …
```
=> chore: sort `polycli loadtest` modes

cmd/monitor/monitor.go
This PR fixes an issue where `polycli monitor` will infinitely hang in cases where it can connect to a valid RPC endpoint, but does not receive valid responses. This PR allows monitor to receive those errors and return them and exit after a `5` second waiting time for the UI to render. 
The RPC is valid, so monitor will continue attempting to render the UI, but the responses will be invalid. So it will never load and be stuck in this state.
`polycli monitor` should now return the error message and exit. This image shows a test with a custom error.
=> fix: return error instead of infinitely hanging monitor

cmd/monitor/cmd.go, cmd/monitor/monitor.go
This PR silences the usage output when an error is returned in `polycli monitor`
The usage for `polycli monitor` is returned along with the error.
Only the error is returned.
=> feat: silence usage when error returned for monitor

.github/workflows/ci.yml, .github/workflows/release.yml, Dockerfile
Follow up of https://github.com/0xPolygon/polygon-cli/pull/399
x
x
=> ci: bump go version from 1.21 to 1.22

cmd/p2p/sensor/sensor.go, doc/polycli_p2p_sensor.md
- Made some revisions to discovery dns implementation
- Fix force add peer
- [DVT-000]()
```bash
go run main.go p2p sensor nodes.json \
--network-id 137 \
--sensor-id mvu \
--write-blocks=false \
--write-block-events=false \
--write-txs=false \
--write-tx-events=false \
--rpc "https://polygon-rpc.com" \
--discovery-dns "enrtree://AKUEZKN7PSKVNR65FZDHECMKOJQSGPARGTPPBI7WS2VUL4EGR6XPC@pos.polygon-peers.io" \
--verbosity 700 --quick-start --key "d8168fb642add845920b91291ec8bbf7c4d5dd2aeaed330fb9e75d766b957f53"
```
=> fix: discovery dns

.gitignore, cmd/p2p/sensor/sensor.go, doc/polycli_p2p_sensor.md
new features:
- on start, force add all enodes from Polygon's dns discovery, dramatically increasing peer count to several hundred peers
- add hourly ticker to recurrently add new peers from DNS ENR tree 
smoke tests locally working as expected and seeing several hundred peers via prometheus port:
`go run main.go p2p sensor nodes.json \
--network-id 137 \
--sensor-id mvu \
--write-blocks=false \
--write-block-events=false \
--write-txs=false \
--write-tx-events=false \
--rpc "https://polygon-rpc.com" \
--discovery-dns "enrtree://AKUEZKN7PSKVNR65FZDHECMKOJQSGPARGTPPBI7WS2VUL4EGR6XPC@pos.polygon-peers.io" \
--verbosity 700 --quick-start --key "d8168fb642add845920b91291ec8bbf7c4d5dd2aeaed330fb9e75d766b957f53"`
=> add dns discovery to sensor logic

cmd/p2p/sensor/sensor.go, p2p/database/datastore.go
- [DVT-000]()
```
go run main.go p2p sensor nodes.json \
--bootnodes "enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303,enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303" \
--network-id 137 \
--sensor-id mvu \
--database-id "" \
--write-blocks=false \
--write-block-events=false \
--write-txs=false \
--write-tx-events=false \
--write-peers=true \
--key-file "mvu.key" \
--rpc "https://polygon-rpc.com" \
--verbosity 700 --quick-start
```
=> chore: change peers caps to []string and change DNS discovery logic

cmd/p2p/sensor/sensor.go, p2p/database/database.go, p2p/database/datastore.go, p2p/protocol.go
=> fix: time first seen timestamps

cmd/monitor/monitor.go, cmd/monitor/ui/ui.go, util/util.go
This PR introduces a new monitor section which currently shows the ForkID. In the future, the same section could be used to add more on-chain information including the:
- Rollup address
- Rollup manager address
This will allow users to easily identify these information in a single UI.
=> feat: add forkid to monitor

cmd/loadtest/loadtest.go
Currently, their functionality is reversed, confusing 
```
pr, random-precompile - Call random precompiled contracts
px, specific-precompile - Call specific precompiled contracts
```
=> fix loadtest param, specific precompile should pass useSelectedAddress=true

cmd/monitor/monitor.go, cmd/monitor/ui/ui.go, util/util.go
This PR adds two additional metrics to the monitor UI, following #429 :
- Rollup Address
- Rollup Manager Address
The above addresses are retrieved by using the new [zkEVM API calls](https://github.com/0xPolygonHermez/cdk-erigon/pull/1447). This will only work on CDK Erigon images which have that PR merged in.
Tested locally with Kurtosis  CDK
=> feat: add rollup address and rollup manager address in monitor

cmd/retest/retest.go, cmd/wrapcontract/usage.md, cmd/wrapcontract/wrapcontract.go, doc/polycli_wrap-contract.md, util/util.go
Add storage initialization + read bytecode from file to the wrap-contract command
=> Add storage initialization + read bytecode from file to wrap-contract

Makefile
When tagging a new release, the current CI suddenly seems to be [failing](https://github.com/0xPolygon/polygon-cli/actions/runs/12800970614/job/35692249637). This PR changes the `-static-libgo` flag to `-static` which allows the cross build to [pass](https://github.com/jhkimqd/polygon-cli/actions/runs/12803011877/job/35695011052).
=> fix: cross compile when building

cmd/fund/fund.go, docutil/readme.go, p2p/database/datastore.go, p2p/protocol.go
fix some function names in comment
- [DVT-000]()
=> chore: fix some function names in comment

cmd/ecrecover/ecrecover.go, doc/polycli_ecrecover.md, util/util.go
Adds --tx option to ecrecover by transaction (hex format). It is exclusive with --block-number and --file. Also, --file is exclusive with --rpc-url
https://github.com/orgs/0xPolygon/projects/13/views/6?pane=issue&itemId=94575989
```
polycli ecrecover --tx 
0x02f86e8205390284014740d385174876e800830186a09400000000000000000000000000000000000000000180c001a05850bab315b686a2bee6ba91b869867ca2f25e612d9ee771588e9efd10a4d3b8a0157972512263193e7a96f2
2c2269691733012d98cd715a9528fed02003260198
```
```
polycli ecrecover --rpc-url https://polygon-rpc.com -b 12345678
0x0375b2fc7140977c9c76D45421564e354ED42277
```
```
polycli ecrecover -t 0xdeadbeef
10:24AM ERR Unable to decode transaction error="rlp: value size exceeds available input length"
```
```
polycli ecrecover --rpc-url https://polygon-rpc.com …
```
=> ecrecover for transactions

cmd/ulxly/ulxly.go
closes https://github.com/0xPolygon/devtools/issues/82
improve invalid `--private-key` error for `ulxly` commands
=> improve invalid --private-key error

cmd/cdk/cdk.go, cmd/dumpblocks/dumpblocks.go, cmd/ecrecover/ecrecover.go, cmd/fixnoncegap/fixnoncegap.go, cmd/flag_loader/flag_loader.go, cmd/flag_loader/flag_loader_test.go, cmd/fund/cmd.go, cmd/loadtest/app.go, cmd/monitor/cmd.go, cmd/nodekey/nodekey.go, cmd/rpcfuzz/cmd.go, cmd/signer/signer.go, cmd/ulxly/ulxly.go
closes https://github.com/0xPolygon/polygon-cli/issues/521
allows current commands that depend on `--rpc-url` and `--private-key` flags to be set via env vars `ETH_RPC_URL` and `PRIVATE_KEY` respectively.
call any command that depends on `--rpc-url` or `--private-key` replacing the flag by the respective env var, the execution must happen exactly the same.
example:
```bash
cdk ger dump --rpc-url https://sepolia.infura.io/v3/f694519bed4a476bbe8905b8c2e00ace --rollup-manager-address bali
$ ETH_RPC_URL="https://sepolia.infura.io/v3/f694519bed4a476bbe8905b8c2e00ace" cdk ger dump --rollup-manager-address bali
$ export ETH_RPC_URL="https://sepolia.infura.io/v3/f694519bed4a476bbe8905b8c2e00ace"
$ cdk ger dump --rollup-manager-address bali
```
=> add a flag loader to allow flags to be set also via env vars

cmd/monitor/ui/ui.go
Fix the block view to show the method `Contract Creation` without overflowing.
closes https://github.com/0xPolygon/polygon-cli/issues/532
=> change tx method column size from 5 to 20

cmd/retest/retest.go, cmd/ulxly/ClaimAssetUsage.md, cmd/ulxly/ClaimMessageUsage.md, doc/polycli_ulxly_claim_asset.md, doc/polycli_ulxly_claim_message.md
=> chore: fix some typos

.github/workflows/ci.yml, cmd/monitor/monitor.go, cmd/monitor/ui/ui.go
closes https://github.com/0xPolygon/polygon-cli/issues/543
It prevents the UI from panicking during the loading when the page-down key is pressed, and the selected block is not set yet.
extra:
- adds a mechanism to avoid calling the `peerCount` endpoint infinitely when its not available, there is not specific issue for that, but it follows the same idea as this https://github.com/0xPolygon/polygon-cli/issues/552
=> fix: monitor pagedown panic

cmd/wallet/wallet.go, doc/polycli_wallet.md, hdwallet/hdwallet.go, hdwallet/hdwallet_test.go
This PR fixes a [bug](https://github.com/0xPolygon/polygon-cli/issues/564) in Ethereum address generation where the x or y coordinate of the public key could have leading zeros removed by big.Int.Bytes(). That led to occasional incorrect addresses. By left-padding each coordinate to 32 bytes, we ensure the uncompressed public key is always 64 bytes before hashing, yielding consistent and correct Ethereum addresses.
=> Fix Address Generation by Properly Left-Padding Public Key Coordinates

cmd/ulxly/ulxly.go
Fix nonce used when claiming everything, as it was using nonce from target for the bridge instead address used to send the tx.
=> Set right nonce from private key instead bridge destination

.github/workflows/ci.yml
The concurrency block in our workflows is used to prevent duplicate or overlapping runs for the same workflow and branch or PR. The issue was that this setup also cancelled previous jobs on the main branch, which was not intended. This PR updates the configuration so that job cancellation only happens for PRs, ensuring all runs on the main branch are preserved.
This PR removes the concurrency block from the nightly workflow, allowing multiple scheduled or manually triggered nightly runs to execute independently without cancelling each other.
=> ci: update concurrency setting

cmd/ulxly/ulxly.go
- Add deposit count number for `polycli ulxly bridge` commands 
- This feature will be particularly useful to make bridge claims without needing to query the bridge service
An example bridge transaction receipt looks like:
```
blockHash            0xe4ec674ea1ad313614a4c3a52bf5b344a9a266504708d6211cae229253f8fc29
blockNumber          1497
contractAddress      
cumulativeGasUsed    171945
effectiveGasPrice    8
from                 0xE34aaF64b29273B7D567FCFc40544c014EEe9970
gasUsed              171945
logs                 [{"address":"0x927aa8656b3a541617ef3fba4a2ab71320dc7fd7","topics":["0x501781209a1f8899323b96b4ef08b168df93e0a90c673d1e4cce39366cb62f9b"],"data":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> feat: add deposit count info in ulxly bridge

cmd/ulxly/ulxly.go
- Log input calldata for `polycli ulxly bridge` command if the transaction is reverted
Create a massive calldata file first with 
```
xxd -p /dev/zero | tr -d "\n" | head -c 97000 > /tmp/test.hex
```
Then trigger bridging with
```
polycli ulxly bridge asset --rpc-url http://$(kurtosis port print op el-1-geth-lighthouse rpc) --destination-network 1 --destination-address 0xE34aaF64b29273B7D567FCFc40544c014EEe9970 --token-address 0x22939b3A4dFD9Fc6211F99Cdc6bd9f6708ae2956 --call-data-file /tmp/test.hex --force-update-root=false --value 0 --bridge-address 0x927aa8656B3a541617Ef3fBa4A2AB71320dc7fD7 --private-key 12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625
```
=> feat: log calldata if revert

cmd/flag_loader/flag_loader.go, cmd/fund/cmd.go, cmd/fund/fund.go, cmd/loadtest/app.go, cmd/loadtest/loadtest.go, doc/polycli_fund.md, doc/polycli_loadtest.md
In case SendOnly is enabled for load testing, no light summary is provided. But the test still calls recordSample, which does not make sense, and eats all the RAM during long heavy load testing.
Disable light summary if SendOnly is enabled.
=> fix: Disable sample recording if SendOnly is enabled for load testing
