- README.md
- cmd/fork/fork.go
- cmd/root.go
Creating a script to take a forked block hash and work it's way back the chain until it reaches a canonical block
I ran this against `39599624` from mainnet and was able to export blocks from side chain and canonical as expected.
> Fork Analysis

- cmd/monitor/monitor.go
- `PGUP` and `PGDN` for navigating by a window size
- `gg` and `HOME` to go to the newest block
- `G` and `END` to go to the oldest block
- Older blocks will be fetched at the same time new blocks are requested, so if you don't see the older blocks when navigating right away, you may want to decrease the `--interval`. Do `ESC` to refresh the list and `G` to go to the oldest block.
```
go run main.go monitor https://polygon-rpc.com -v 500 -b 2 2> monitor.log
```
> add history queries and new key-binds

- README.md
- cmd/p2p/client/client.go
- cmd/p2p/client/client_util.go
- cmd/p2p/crawl/crawl.go
- cmd/p2p/p2p.go
- cmd/p2p/ping/ping.go
- p2p/nodeset.go
- p2p/rlpx.go
- p2p/types.go
- Adds `--listen` flag to `p2p ping` which will not close the connection after the `Hello` and `Status` message exchange. It will keep the connection open and receive and process messages.
- Adds `client` command which will watch for blocks and transactions after discovering peers.
- [DVT-590](https://polygon.atlassian.net/browse/DVT-590)
- [DVT-591](https://polygon.atlassian.net/browse/DVT-591)
```
go run main.go p2p ping "enode://4bf93e09f29480e895ce42c64b8cfac2de47b45f04e16b7ee447cc88aeaf051eecf7cd083b07820dfb95c37f0ec491afe043f420a4e7f79587064e65705f32de@3.138.36.71:30303"
```
```
go run main.go p2p client nodes.json --crawl=true --bootnodes enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55 …
```
> [DVT-590][DVT-591] Add p2p ping and client commands

- p2p/rlpx.go
- Sometimes nodes will send a `GetBlockHeaders` or `GetBlockBodies` request and the light client can't respond as we don't store that data in memory. This PR implements a workaround to just send back an empty response with the `RequestID` that will prevent many of the `useless peer` disconnects.
- [DVT-590](https://polygon.atlassian.net/browse/DVT-590)
[DVT-590]: https://polygon.atlassian.net/browse/DVT-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DVT-590] Fix useless peers

- .github/workflows/test.yml
- Makefile
Our CI pipeline was only running go linters but not tests. This PR aims to fix this.
x
> ci: run go tests in ci

- cmd/monitor/monitor.go
- fixes batch off by one error
> fix monitor off by one

- p2p/database/database.go
- p2p/database/datastore.go
- p2p/rlpx.go
- p2p/types.go
- Fetches missing parent blocks so that the chain will remain unbroken
- [DVT-789](https://polygon.atlassian.net/browse/DVT-789)
[DVT-789]: https://polygon.atlassian.net/browse/DVT-789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DVT-789] Fetch missing parent blocks

- p2p/database/datastore.go
- p2p/rlpx.go
- Use datastore `RunInTransaction` to stop race condition
- [DVT-789](https://polygon.atlassian.net/browse/DVT-789)
```
44070126
44070127
44070127
depth      from        to  signers                                          from_hash                                            to_hash
0     26  44094833  44094858        1  0xb73c261235365099e0ae8e6012901e24b1de5f8bb33d...  0x34858be00e2137464ba534685377ad6503de531a423b...
1     22  44095637  44095658        1  0x3265bca05dd4b0a0bba58bd289be36066a5e65cb10d9...  0xa2e85e8f90d1ef5f85567c712938993730d5ee0d8b05...
3     21  44091851  44091871        1  0x3fe29a48be98996622b3e9e3754656132659d60082fe...  0xe01bf1240f321eb7df27f477fea39bab7ee6dd3da740...
4     21  44098875  44098895        1  0xdf8898f4936bef34ece503d1d7e869f78ea2d4c6ddb3... …
```
> [DVT-789] Fix datastore race condition

- cmd/forge/forge.go
- cmd/fork/fork.go
- cmd/loadtest/loadtest.go
- cmd/monitor/monitor.go
- cmd/p2p/p2p.go
- cmd/p2p/ping/ping.go
- cmd/root.go
- Removes duplication for logging and adds global `--verbosity` and `--pretty-logs` flags.
- [DVT-802](https://polygon.atlassian.net/browse/DVT-802)
```bash
go run main.go (fork|forge|loadtest|monitor|ping)
```
```bash
go run main.go p2p ping "enode://bdcd4786a616a853b8a041f53496d853c68d99d54ff305615cd91c03cd56895e0a7f6e9f35dbf89131044e2114a9a782b792b5661e3aff07faf125a98606a071@3.145.169.141:30303" --pretty-logs=false
```
[DVT-802]: https://polygon.atlassian.net/browse/DVT-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DVT-802] Standardize logging

- cmd/rpcfuzz/rpcfuzz.go
- fix something that conflicts with the `--pretty-logs` flag
- [DVT-000]()
> remove duplicate pretty log setting

- cmd/loadtest/loadtest.go
The adaptive rate limiter wouldn't always stop after the test is finished. To fix the issue, the `updateRateLimit` method now takes a `context` parameter to terminate the goroutine.
- [DVT-797]()
[DVT-797]: https://polygon.atlassian.net/browse/DVT-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: stop adaptive rate limit after the test is finished

- Makefile
> fixed makefile copy binary bug

- metrics/metrics.go
- rpctypes/rpctypes.go
Make polycli monitor eip-1559 aware for transactions
* gas fee
* gas tip
* tx type
> 1559 aware monitor variables

- Makefile
- README.md
- cmd/abi/abi.go
- cmd/loadtest/loadtest.go
- cmd/rpcfuzz/rpcfuzz.go
> fix: messages

- README.md
- Add summary
- Reorganise `README` according to the order defined by `polycli -h`
- Document `parseethwallet` cmd
> doc: add summary and reorganise `README`

- Makefile
- dashboard/dashboard.go
- hdwallet/hdwallet.go
- rpctypes/rpctypes.go
- rpctypes/schemas/openrpc.json
Fixed some typos in go and jsonfiles
> fixed go files

- cmd/loadtest/loadtest.go
- cmd/monitor/monitor.go
I ran into some issues with the fee calculations while testing. It looks like there is a bug were we're inadvertently setting the price to be the tip. I'm fixing that and also adding logic that the tip doesn't exceed the base fee since that was causing issues with the pricing for some reason.
> Polycli Fee Fixes

- cmd/loadtest/uniswapv3.go
- doc/polycli_loadtest_uniswapv3.md
> doc: update `loadtest uniswapv3` usage

- .github/workflows/release.yml
> chore: clean up `release` job

- p2p/protocol.go
- p2p/rlpx.go
- Fixes `p2p ping` protocol version
- Fixes status message protocol version
- [DVT-1060](https://polygon.atlassian.net/browse/DVT-1060)
[DVT-1060]: https://polygon.atlassian.net/browse/DVT-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DVT-1060] Fix status message protocol version

- README.md
- cmd/monitor/cmd.go
- cmd/monitor/monitor.go
- doc/polycli_monitor.md
- go.mod
- go.sum
Reverts maticnetwork/polygon-cli#148
> Revert "DVT-1057 replace block data structure with LRU cache to fix memory leak"

- cmd/loadtest/uniswapv3/swap.go
It's in the title :)
- [DVT-1074](https://polygon.atlassian.net/browse/DVT-1074)
No tests required!
[DVT-1074]: https://polygon.atlassian.net/browse/DVT-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: drop successful swap msg to trace level in `uniswapv3` mode

- cmd/loadtest/loadtest.go
Get a random transaction hash and calculate the estimated gas cost for it.
- [DVT-1123](https://polygon.atlassian.net/browse/DVT-1123)
[DVT-1123]: https://polygon.atlassian.net/browse/DVT-1123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: implement `eth_estimateGas` in `polycli loadtest --mode rpc`

- Makefile
- scripts/clients.mk
Run `polycli` with the data race detector enabled in CI.
- [DVT-1203](https://polygon.atlassian.net/browse/DVT-1203)
x
[DVT-1203]: https://polygon.atlassian.net/browse/DVT-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: run `polycli` with the data race detector enabled in CI

- cmd/dumpblocks/dumpblocks.go
- cmd/dumpblocks/usage.md
- doc/polycli_dumpblocks.md
Switch from `polycli dumpblocks <url> <start> <end>` to `polycli dumpblocks <start> <end> --rpc-url <url>` to match `cast` and other `polycli` commands structure.
- [DVT-1211](https://polygon.atlassian.net/browse/DVT-1211)
```sh
$ polycli dumpblocks 0 2 --rpc-url http://localhost:8545     
11:57AM INF Thread count thread=1
11:57AM INF Getting range end=2 start=0
11:57AM INF Finished requesting data starting to wait
{"hash":"0x494e12137cc9892f2c3238a906d359dd5ba2fb187ed70f3660e13cbe4395f17f","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","trans …
```
> chore: add `rpc-url` flag to `dumpblocks`

- .github/workflows/build-docker.yml
- .github/workflows/build-package.yml
- .github/workflows/security-build.yml
- Dockerfile
Follow up of #189 
- [DVT-1261](https://polygon.atlassian.net/browse/DVT-1261)
[DVT-1261]: https://polygon.atlassian.net/browse/DVT-1261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: security build issue

- cmd/p2p/sensor/sensor.go
- doc/polycli_p2p_sensor.md
- p2p/protocol.go
- Removes used genesis flag
- [DVT-000]()
> chore: remove genesis flag

- cmd/monitor/ui/ui.go
- rpctypes/rpctypes.go
This PR includes new blob parameters shown by the execution client:
- `blobGasPrice`
- `blobGasUsed`
and includes UI cleanup, and addition of `Blob` as transaction method  
- [DVT-1519](https://polygon.atlassian.net/browse/DVT-1519)
[DVT-1519]: https://polygon.atlassian.net/browse/DVT-1519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: loadtest monitor new blob params + ui cleanup

- cmd/loadtest/loadtest.go
Check for duplicate inputs during `loadtest` and throw error.
> feat: loadtest check for duplicate mode input

- cmd/p2p/crawl/crawl.go
- cmd/p2p/crawl/crawl_util.go
- cmd/p2p/ping/ping.go
- cmd/p2p/sensor/sensor.go
- doc/polycli_p2p_crawl.md
- p2p/nodeset.go
- Improve crawl to gather more data
- [DVT-1516](https://polygon.atlassian.net/browse/DVT-1516)
[DVT-1516]: https://polygon.atlassian.net/browse/DVT-1516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: improve crawl analysis

- README.md
Adding Polygon R&D Discord Server Link to all the Polygon Tech Repositories.
> Adding Polygon R&D Discord link

- cmd/p2p/sensor/sensor.go
- p2p/protocol.go
> feat: add name metric label

- cmd/ulxly/ulxly.go
- contracts/Makefile
> chore: include ulxly gen bindings and lint

- cmd/ulxly/ulxly.go
- Use logger instead of `fmt.Print`.
- Fix a few lint issues.
x
x
> chore: `ulxly` minor changes

- cmd/p2p/sensor/sensor.go
- doc/polycli_p2p_sensor.md
- p2p/database/database.go
- p2p/database/datastore.go
> feat: write peers to datastore

- cmd/monitor/ui/ui.go
This PR introduces conditions to check if the `ContractAddress`, `Root`, `BlobGasPrice`, and `BlobGasUsed` fields are non-zero, and only includes these fields if the values are populated.
These values would otherwise always show zero values, which could be a source of confusion.
> chore: minor changes to monitor receipt view to output non-empty metrics

- cmd/retest/retest.go
- cmd/retest/usage.md
- doc/polycli_retest.md
Introduce necessary steps to inject storage initialization bytecode into the SC bytecode.
Also adds option to specify solc binary -if you using solcx or something like that- by setting env var SOLC_PATH
> Storage initialization for retest

- .github/workflows/ci.yml
Related to #401 
- Fix the failing `go install github.com/0xPolygon/polygon-cli@latest` job.
- Also make this job required.
x
x
> fix: go-install job

- p2p/database/datastore.go
- A high number of retry attemps may cause the number of goroutines to be high
- [DVT-000]()
> fix: reduce max attempts

- cmd/p2p/sensor/sensor.go
- p2p/database/database.go
- p2p/database/datastore.go
- p2p/protocol.go
timestamp data collected immediately at arrival, not after goroutine has been spawned downstream
smoke tests: 
- sensors run locally with timestamp changes: no errors running program
- still unclear how to test event writing locally (to ensure data results clean)
> sensor fix: accurately timestamp data on arrival

- cmd/wrapcontract/wrapcontract.go
Fix wrap-contract when reading content from file
> Fix wrap-contract when reading content from file

- cmd/ulxly/ulxly.go
Making some minor changes to the `ulxly claim --wait` option in order to make sure the proof is initialized properly and that we wait if the deposit hasn't been synced yet.
> fix: minor ordering issues with waiting code

- p2p/database/database.go
fix struct name in comment
- [DVT-000]()
> chore: fix struct name in comment

- cmd/retest/retest.go
make function comment match function name
- [DVT-000]()
> chore: make function comment match function name

- cmd/nodekey/nodekey.go
- cmd/signer/signer.go
close https://github.com/0xPolygon/polygon-cli/issues/573
fix loading private key flag for signer and node commands
> fix loading private key flag for signer and node commands

- cmd/foldtrace/usage.md
- doc/polycli_fold-trace.md
fix some typos in comment
- [DVT-000]()
> chore: fix some typos in comment

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Pin tag for non-immutable actions.
- Add permissions.
https://github.com/0xPolygon/polygon-cli/security/code-scanning
> fix: workflows security issues

- cmd/ulxly/claimGetUsage.md
- cmd/ulxly/ulxly.go
- doc/polycli_ulxly.md
- doc/polycli_ulxly_get-claims.md
Closes #593 
This PR adds a new uLxLy command to get all the claim events
> read claim events

- rpctypes/rpctypes.go
Copy/paste of #605 with verified commits
> chore: fix typos
